# Generated by Django 6.0.2 on 2026-02-08 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=512)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('modified_at', models.DateTimeField()),
                ('is_dir', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
