# Generated by Django 6.0.2 on 2026-02-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='owner',
            field=models.CharField(blank=True, default='system', max_length=100),
        ),
    ]
